# Generated by Django 5.1.6 on 2025-02-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pword', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'admin_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('post_content', models.TextField()),
                ('date_posted', models.DateTimeField()),
            ],
            options={
                'db_table': 'blog_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'college',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nandu',
            fields=[
                ('nandu_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_year', models.IntegerField()),
                ('nandu_string', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nandu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('events_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_year', models.IntegerField()),
                ('register_date', models.DateTimeField()),
                ('paid', models.BooleanField()),
                ('changquan', models.BooleanField(blank=True, null=True)),
                ('nanquan', models.BooleanField(blank=True, null=True)),
                ('changquan_nandu', models.BooleanField(blank=True, null=True)),
                ('nanquan_nandu', models.BooleanField(blank=True, null=True)),
                ('b_sword', models.BooleanField(blank=True, null=True)),
                ('s_sword', models.BooleanField(blank=True, null=True)),
                ('nandao', models.BooleanField(blank=True, null=True)),
                ('staff', models.BooleanField(blank=True, null=True)),
                ('spear', models.BooleanField(blank=True, null=True)),
                ('nangun', models.BooleanField(blank=True, null=True)),
                ('o_bare', models.BooleanField(blank=True, null=True)),
                ('o_weapon', models.BooleanField(blank=True, null=True)),
                ('taiji_24', models.BooleanField(blank=True, null=True)),
                ('yang', models.BooleanField(blank=True, null=True)),
                ('chen', models.BooleanField(blank=True, null=True)),
                ('fist_42', models.BooleanField(blank=True, null=True)),
                ('sword_42', models.BooleanField(blank=True, null=True)),
                ('taiji_weapon', models.BooleanField(blank=True, null=True)),
                ('int_o_weapon', models.BooleanField(blank=True, null=True)),
                ('int_o_bare', models.BooleanField(blank=True, null=True)),
                ('taiji_bare_nandu', models.BooleanField(blank=True, null=True)),
                ('trad_bare', models.BooleanField(blank=True, null=True)),
                ('trad_long', models.BooleanField(blank=True, null=True)),
                ('trad_short', models.BooleanField(blank=True, null=True)),
                ('trad_soft', models.BooleanField(blank=True, null=True)),
                ('group_set', models.BooleanField(blank=True, null=True)),
                ('group_set_id', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registered_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_year', models.IntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pword', models.CharField(max_length=32)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('grad_date', models.DateField()),
                ('student_type', models.CharField(max_length=1)),
                ('class_type', models.CharField(max_length=1)),
                ('xp', models.CharField(max_length=1)),
                ('first_comp_year', models.IntegerField()),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
    ]
